### ISSUE TITLE
Canonical url

### ISSUE THREAD

**Issue by avive** [spacemeshos/ws-ops#23]
Please make discovery service more friendly to humans by having https://discover.spacemesh.io display content of discovery json e.g.: https://discover.spacemesh.io/networks.json instead of the repo technical readme, ideally w/o modifying the url in the browser. It is also fine to okay to networks.json

**Comment by valar999** [comment]
Done, but it shows content without `Content-Type: application/json`.
https://discover.spacemesh.io works on GitHub Pages and there is no way to set Content-Type for root file.
