### ISSUE TITLE
json api

### ISSUE THREAD

**Issue by avive** [spacemeshos/ws-ops#3]
Json api endpoint e.g.  "jsonAPI": "https://api-json-20.spacemesh.io/ " in the discovery service should be the json api gateway over the new grpc api and not the old spacemesh grpc api. For api availability, we should use the mesh netId endpoint until we have the grpc health service implemented and working.

**Comment by avive** [comment]
@valar999 - is this fixed?

**Comment by valar999** [comment]
It's fixed
